ci: cleanup workflows (#327)

diff --git a/.github/workflows/typos.yml b/.github/workflows/typos.yml
--- a/.github/workflows/typos.yml
+++ b/.github/workflows/typos.yml
@@ -11,18 +11,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-    - uses: crate-ci/typos@master
-      id: typos
-      continue-on-error: true
+      - uses: actions/checkout@v4
 
-    # 'continue-on-error' will always succeed, we should exit based on the outcome and not the conclusion
-    # ref: https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
-    - name: Fail when typos are found in pull request
-      if: ${{ github.event_name == 'pull_request' && steps.typos.outcome != 'success' }}
-      run: "exit 1"
+      - name: Check for typos
+        uses: crate-ci/typos@master
+        id: typos
+        continue-on-error: true
 
-    # We always want this check to pass on branch 'main' but continue to fail on PRs
-    - name: Pass on 'main' branch
-      if: ${{ github.repository == 'catppuccin/userstyles' && github.ref == 'refs/heads/main' }}
-      run: "exit 0"
+      # 'continue-on-error' will always succeed, we should exit based on the outcome and not the conclusion
+      # ref: https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
+      - name: Fail when typos are found in pull request
+        if: ${{ github.event_name == 'pull_request' && steps.typos.outcome != 'success' }}
+        run: "exit 1"
+
+      # We always want this check to pass on branch 'main' but continue to fail on PRs
+      - name: Pass on 'main' branch
+        if: ${{ github.repository == 'catppuccin/userstyles' && github.ref == 'refs/heads/main' }}
+        run: "exit 0"
